<form action="<?= _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken(); ?>" />
	<legend><?= _t('ext.reddit_image.section.display_options') ?></legend>
	<div class="form-group">
		<label class="group-name" for="image-height"><?= _t('ext.reddit_image.image_height'); ?></label>
		<div class="group-controls">
            <input type="number" name="image-height" id="image-height" value="<?= $this->getImageHeight(); ?>" min="1" max="1000"/>
            <?= _t('ext.reddit_image.image_height_unit'); ?>
		</div>
	</div>

	<div class="form-group">
		<div class="group-controls">
			<label class="checkbox" for="muted-video">
				<input type="checkbox" name="muted-video" id="muted-video" value="1" <?= $this->getMutedVideo() ? 'checked=true' : '' ?>/>
				<?= _t('ext.reddit_image.muted_video'); ?>
			</label>
		</div>
	</div>

	<div class="form-group">
		<div class="group-controls">
			<label class="checkbox" for="display-image">
				<input type="checkbox" name="display-image" id="display-image" value="1" <?= $this->getDisplayImage() ? 'checked=true' : '' ?>/>
				<?= _t('ext.reddit_image.display_image'); ?>
			</label>
		</div>
	</div>

	<div class="form-group">
		<div class="group-controls">
			<label class="checkbox" for="display-video">
				<input type="checkbox" name="display-video" id="display-video" value="1" <?= $this->getDisplayVideo() ? 'checked=true' : '' ?>/>
				<?= _t('ext.reddit_image.display_video'); ?>
			</label>
		</div>
	</div>

	<div class="form-group">
		<div class="group-controls">
			<label class="checkbox" for="display-original">
				<input type="checkbox" name="display-original" id="display-original" value="1" <?= $this->getDisplayOriginal() ? 'checked=true' : '' ?>/>
				<?= _t('ext.reddit_image.display_original'); ?>
			</label>
		</div>
	</div>

	<div class="form-group">
		<div class="group-controls">
			<label class="checkbox" for="display-metadata">
				<input type="checkbox" name="display-metadata" id="display-metadata" value="1" <?= $this->getDisplayMetadata() ? 'checked=true' : '' ?>/>
				<?= _t('ext.reddit_image.display_metadata'); ?>
			</label>
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?= _t('gen.action.submit'); ?></button>
			<button type="reset" class="btn"><?= _t('gen.action.cancel'); ?></button>
		</div>
	</div>

	<legend><?= _t('ext.reddit_image.section.authorizations') ?></legend>
	<div class="form-group">
		<label class="group-name" for="imgur-client-id"><?= _t('ext.reddit_image.imgur_client_id'); ?></label>
		<div class="group-controls">
			<input type="text" name="imgur-client-id" id="imgur-client-id" value="<?= $this->getImgurClientId() ?>"/>
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?= _t('gen.action.submit'); ?></button>
			<button type="reset" class="btn"><?= _t('gen.action.cancel'); ?></button>
		</div>
	</div>
</form>
